flaskblog/models.py
from datetime import datetime
from flaskblog import db, login_manager
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), nullable=False, unique=True)
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return False
        return User.query.get(user_id)

    def get_reset_token(self, expires_in=1800):
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=expires_in)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError, BooleanField
from wtforms.validators import DataRequired, EqualTo, Email, Length

from flaskblog.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken.')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField(' Remember Me')
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Update')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken.')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

flaskblog/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy

from flaskblog.config import Config

bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
db = SQLAlchemy()
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from flaskblog.users.routes import users
    from flaskblog.posts.routes import posts
    from flaskblog.main.routes import main
    from flaskblog.errors.handlers import errors

    app.register_blueprint(posts)
    app.register_blueprint(users)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    return app

flaskblog/main/routes.py
from flask import Blueprint, request, render_template

from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import Blueprint, flash, redirect, render_template, abort, url_for, request
from flask_login import login_required, current_user

from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, action_heading='New Post')


@posts.route("/post/<post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<post_id>/update", methods=['GET', 'POST'])
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, action_heading='Update Post')


@posts.route("/post/<post_id>/delete", methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, redirect, flash, url_for, render_template, request
from flask_login import current_user, login_user, logout_user, login_required

from flaskblog import bcrypt, db
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to login', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>About</h1>
</body>
</html>

flaskblog/templates/account.html
{% extends "base.html" %}
{% block content %}
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.1.0/css/all.css">
    <!--div class="content-section"-->
    <div class="media">
        <img src="{{ url_for('static', filename='user-1_256.png') }}" class="rounded-circle account-img"
             style="width: 80px;height: 80px">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>

    <div class="login-clean" style="margin-top: -60px; ">
        <form method="POST" class="acc_form" style="height:600px;width:500px;border-radius: 25px;" action="">
            {{ form.hidden_tag() }}
            <div class="illustration" style="">
                <h3 class="text text-center text-dark">Update Account</h3>
                <i class="fal fa-user-edit" style="font-size: 70px;margin-top: 10px;"></i>
            </div>
            <div class="form-group">
                {% if form.username.errors %}
                    {{ form.username(class="form-control is-invalid", placeholder="Username") }}
                    {% for error in form.username.errors %}
                        <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.username(class="form-control", placeholder="Username") }}
                {% endif %}
            </div>

            <div class="form-group">
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid",placeholder="Email") }}
                    {% for error in form.email.errors %}
                        <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.email(class="form-control", placeholder="Email") }}

                {% endif %}
            </div>
            <div class="form-group">
                <!--button class="btn btn-primary btn-block" type="submit">Sign Up</button-->
                {{ form.submit(class="btn btn-primary btn-block") }}

            </div>

        </form>


    </div>
    <!--/div-->
{% endblock content %}

flaskblog/templates/account_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>My Blog - {{ title }}</title>
    {% else %}
        <title>My Blog</title>
    {% endif %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='Login-Form-Clean.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='errors.css') }}">

</head>
<body style="background-color:#f1f7fc ">
{% block content %}{% endblock %}
</body>
<!--link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.1.0/css/all.css"-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>

</html>

flaskblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='Login-Form-Clean.css') }}">
    {% if title %}
        <title>My Blog - {{ title }}</title>
    {% else %}
        <title>My Blog</title>
    {% endif %}
</head>
<body style="background-color: #f1f7fc">
<header>
    <nav class="navbar navbar-dark bg-primary navbar-expand-md">
        <div class="container-fluid"><a class="navbar-brand" href="{{ url_for('main.home') }}">SIMPLE BLOG </a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse"
                 id="navcol-1">
                <ul class="nav navbar-nav">
                    <li class="nav-item mr-auto" role="presentation"><a class="nav-link "
                                                                        href="{{ url_for('main.home') }}"><i class="fa fa-home" style="font-size: 24px"></i>&nbsp;Home</a></li>
                    <li class="nav-item mr-auto" role="presentation"><a class="nav-link" href="{{ url_for('main.about') }}"><i class="fa fa-user" style="font-size: 23px;margin-top: .1rem;"></i>&nbsp;About</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item mr-auto" role="presentation"><a class="nav-link"
                                                                            href="{{ url_for('posts.new_post') }}"><i
                                class="far fa-edit" style="font-size: 25px;"></i>&nbsp;New Post</a>
                        </li>
                        <li class="nav-item mr-auto" role="presentation"><a class="nav-link "
                                                                            href="{{ url_for('users.account') }}"><i
                                class="fas fa-user-edit" style="font-size: 25px;"></i>&nbsp;Account</a>
                        </li>
                        <li class="nav-item mr-auto" role="presentation"><a class="nav-link pt-1"
                                                                            href="{{ url_for('users.logout') }}"><i class="icon ion-log-out" style="font-size: 23px"></i>&nbsp;Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item mr-auto" role="presentation"><a class="nav-link mb-1 "
                                                                            href="{{ url_for('users.login') }}"><i class="icon ion-log-in" style="font-size: 25px"></i>&nbsp;Login</a></li>
                        <li class="nav-item mr-auto" role="presentation"><a class="nav-link"
                                                                            href="{{ url_for('users.register') }}"><i class="fa fa-user-circle" style="font-size: 24px;margin-top: .5rem"></i>&nbsp;Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<main class="container" role="main">
    <div class="row">
        <div class="col-md-8" style="margin-top: 2rem;">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section" style="margin-top: 2rem;">
                <h3>Heading</h3>
                <p class="text-muted">Paragraph</p>
                <ul class="list-group">
                    <li class="list-group-item first-lst"><span>List Group Item 1</span></li>
                    <li class="list-group-item"><span>List Group Item 2</span></li>
                    <li class="list-group-item third-lst"><span>List Group Item 3</span></li>
                </ul>
            </div>
        </div>
    </div>
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

flaskblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="login-clean" style="margin-top: -30px;">
        <form method="POST" class="acc_form" style="height:600px;max-width:600px;border-radius: 25px;" action="">
            {{ form.hidden_tag() }}
            <div class="illustration" style="">
                <h3 class="text text-center text-primary">{{ heading_action }}</h3>
                <i class="fa fa-edit" style="font-size: 70px;margin-top: 10px;"></i>
            </div>
            <div class="form-group">
                {% if form.title.errors %}
                    {{ form.title(class="form-control is-invalid", placeholder="Title name") }}
                    {% for error in form.title.errors %}
                        <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.title(class="form-control", placeholder="Title name") }}
                {% endif %}
            </div>

            <div class="form-group">
                {% if form.content.errors %}
                    {{ form.content(class="form-control is-invalid post_content",placeholder="Content", rows=10, cols=10) }}
                    {% for error in form.content.errors %}
                        <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.content(class="form-control post_content", placeholder="Content", rows='10', cols='10') }}

                {% endif %}
            </div>
            <div class="form-group">
                <!--button class="btn btn-primary btn-block" type="submit">Sign Up</button-->
                {{ form.submit(class="btn btn-primary btn-block") }}

            </div>

        </form>


    </div>
    {% endblock content %}

flaskblog/templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section" style="border-radius: 15px;background-color: white">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='user.png') }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d %b %Y - %a') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if posts.page==page_num %}
            <a class="btn btn-primary mb-4" href="{{ url_for('main.home', page=page_num) }}"></a>
        {% else %}
            <a class="btn btn-outline-primary mb-4" href="{{ url_for('main.home', page=page_num) }}"></a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}

flaskblog/templates/login.html
{% extends 'account_base.html' %}
{% block content %}
    <div class="login-clean">
        <form method="POST" action="" class="login_form1" style="border-radius: 25px;" enctype="multipart/form-data">
            <div>
                {{ form.hidden_tag() }}
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
            <div class="illustration">
                <h3 class="text text-center text-primary">Login</h3>
                <i class="icon ion-log-in" style="color:#1E90FF;"></i></div>
            <div class="form-group">
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid",placeholder="Email") }}
                    {% for error in form.email.errors %}
                        <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.email(class="form-control", placeholder="Email") }}

                {% endif %}
            </div>
            <div class="form-group">
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid", placeholder="Password") }}
                    {% for error in form.password.errors %}
                        <div class="invalid-feedback">
                        <span>{{ error }}</span>
                    {% endfor %}

                </div>
                {% else %}
                    {{ form.password(class="form-control", placeholder="Password") }}
                {% endif %}
            </div>
            <div class="form-group">
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary btn-block") }}
            </div>
            <span style="font-size:14px;text-align:center">Don't have an account ?&nbsp;<a
                    href="{{ url_for('users.register') }}"
                    style="text-align:center">Sign Up</a></span>
        <br>
        <span style="font-size:14px;text-align:center"><a
                    href="{{ url_for('users.reset_request') }}"
                    style="text-align:center">Forgot your password?&nbsp;</a></span>
        </form>
    </div>
{% endblock %}

flaskblog/templates/post.html
{% extends 'base.html' %}
{% block content %}
    <article class="media content-section" style="border-radius: 15px;background-color: white">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='user.png') }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d %A %Y') }}</small>
                {% if post.author==current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                                data-target="#deleteModal">Delete
                        </button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this post?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <!--button type="button" class="btn btn-primary">Delete</button-->
                    <form action="{{ url_for('posts.delete_post', post_id = post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

flaskblog/templates/user_posts.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="mb-3" style="font-size: 25px;">Posts by {{ user.username }}<span class="text-muted" style="font-size: 15px;">&nbsp;({{ posts.total }})</span></h1>
    {% for post in posts.items %}
        <article class="media content-section" style="border-radius: 15px;background-color: white">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='user.png') }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d %b %Y - %a') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    <div class="center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if posts.page==page_num %}
            <a class="btn btn-primary mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"></a>
        {% else %}
            <a class="btn btn-outline-primary mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}"></a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}